server:
  port: 8080

spring:
  application:
    name: document-service
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.atsresume.docservice: DEBUG
    org.springframework.web: DEBUG 